version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/postgres/dumps/:/tmp/
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: "tg_users"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    restart: always
  redis-data:
    image: redis:alpine
    ports:
      - "127.0.0.1:6380:6379"
    networks:
      - default
volumes:
  database:
    driver: local