version: "3"

services:
  users-db:
    image: postgres:latest
    ports:
      - 5439:5432
    volumes:
      - ./data/users-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tg_users

  tracks-db:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - ./data/tracks-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tg_tracks

  rates-db:
    image: postgres:latest
    ports:
      - 5434:5432
    volumes:
      - ./data/rates-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tg_rates

  posts-db:
    image: postgres:latest
    ports:
      - 5435:5432
    volumes:
      - ./data/posts-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tg_posts

  files-db:
    image: postgres:latest
    ports:
      - 5436:5432
    volumes:
      - ./data/files-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tg_files

  comments-db:
    image: postgres:latest
    ports:
      - 5437:5432
    volumes:
      - ./data/comments-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tg_comments

  hangfire-db:
    image: postgres:latest
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tg_hangfire
