//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashGrounds.User.Infrastructure.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationFailedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationFailedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrashGrounds.User.Infrastructure.Constants.ValidationFailedMessages", typeof(ValidationFailedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALREADY_USED.
        /// </summary>
        public static string AlreadyUsed {
            get {
                return ResourceManager.GetString("AlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIELD_IS_EMPTY.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCORRECT_EMAIL.
        /// </summary>
        public static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIGIT_REQUIRED.
        /// </summary>
        public static string RequiresDigit {
            get {
                return ResourceManager.GetString("RequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOWERCASE_REQUIRED.
        /// </summary>
        public static string RequiresLowercase {
            get {
                return ResourceManager.GetString("RequiresLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON_ALPHANUMERIC_REQUIRED.
        /// </summary>
        public static string RequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("RequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPERCASE_REQUIRED.
        /// </summary>
        public static string RequiresUppercase {
            get {
                return ResourceManager.GetString("RequiresUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIELD_IS_LONG.
        /// </summary>
        public static string TooLongField {
            get {
                return ResourceManager.GetString("TooLongField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIELD_IS_SHORT.
        /// </summary>
        public static string TooShortField {
            get {
                return ResourceManager.GetString("TooShortField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_INVALID.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIELD_WITH_WRONG_SYMBOLS.
        /// </summary>
        public static string WrongSymbols {
            get {
                return ResourceManager.GetString("WrongSymbols", resourceCulture);
            }
        }
    }
}
